# Generated by Django 3.2.5 on 2022-08-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TorznabIndexer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=1024)),
                ('apikey', models.CharField(max_length=128)),
            ],
        ),
    ]
