# Generated by Django 4.1 on 2022-08-27 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hamstery', '0002_tvlibrary'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvDownload',
            fields=[
                ('hash', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='downloads', to='hamstery.tvepisode')),
                ('filename', models.CharField(blank=True, default='', max_length=4096)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='tvepisode',
            name='status',
            field=models.IntegerField(choices=[(1, 'Missing'), (3, 'Ready')]),
        ),
    ]
