# Generated by Django 4.1 on 2022-08-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamstery', '0003_tvdownload_alter_tvepisode_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvdownload',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
