# Generated by Django 4.1 on 2022-09-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamstery', '0004_tvdownload_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='air_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tvepisode',
            name='air_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tvseason',
            name='air_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
