# Generated by Django 4.1 on 2022-12-22 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hamstery', '0009_alter_showsubscription_offset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoredtvdownload',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='downloads', to='hamstery.showsubscription'),
        ),
    ]
