# Generated by Django 4.1 on 2022-12-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamstery', '0010_alter_monitoredtvdownload_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showsubscription',
            name='offset',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
