# Generated by Django 4.1 on 2023-02-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamstery', '0011_alter_showsubscription_offset'),
    ]

    operations = [
        migrations.CreateModel(
            name='HamsterySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qbittorrent_host', models.CharField(blank=True, default='', max_length=2048)),
                ('qbittorrent_port', models.CharField(blank=True, default='', max_length=5)),
                ('qbittorrent_username', models.CharField(blank=True, default='', max_length=255)),
                ('qbittorrent_password', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
