# Generated by Django 4.1 on 2023-02-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamstery', '0012_hamsterysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamsterysettings',
            name='plex_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hamsterysettings',
            name='plex_token',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='hamsterysettings',
            name='plex_url',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
