# Generated by Django 4.2.8 on 2024-01-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hamstery", "0013_hamsterysettings_plex_enable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tvepisode",
            name="warn_removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tvseason",
            name="warn_removed",
            field=models.BooleanField(default=False),
        ),
    ]
