# Generated by Django 4.2.9 on 2024-01-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hamstery", "0014_tvepisode_warn_removed_tvseason_warn_removed"),
    ]

    operations = [
        migrations.CreateModel(
            name="HamsteryStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("openai_title_parser_calls", models.IntegerField(default=0)),
                ("openai_title_parser_failures", models.IntegerField(default=0)),
                (
                    "openai_title_parser_prompt_tokens_used",
                    models.IntegerField(default=0),
                ),
                (
                    "openai_title_parser_completion_tokens_used",
                    models.IntegerField(default=0),
                ),
                (
                    "openai_title_parser_total_tokens_used",
                    models.IntegerField(default=0),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="hamsterysettings",
            name="openai_api_key",
            field=models.CharField(blank=True, default="", max_length=2048),
        ),
        migrations.AddField(
            model_name="hamsterysettings",
            name="openai_title_parser_mode",
            field=models.IntegerField(
                choices=[(1, "Disabled"), (2, "Primary"), (3, "Standby")], default=1
            ),
        ),
        migrations.AddField(
            model_name="hamsterysettings",
            name="openai_title_parser_model",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
