# Generated by Django 4.2.9 on 2024-01-19 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hamstery", "0015_hamsterystats_hamsterysettings_openai_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tvshow",
            name="lib",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                related_name="shows",
                to="hamstery.tvlibrary",
            ),
        ),
    ]
