# Generated by Django 4.2.9 on 2024-01-20 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hamstery", "0016_tvshow_lib"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tvshow",
            name="lib",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                related_name="shows",
                to="hamstery.tvlibrary",
            ),
        ),
    ]
